import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:laundry_jennaira/shared/models/order_model.dart';
import 'package:laundry_jennaira/core/supabase_client.dart';

part 'order_provider.g.dart';

@riverpod
class OrderNotifier extends _$OrderNotifier {
  @override
  FutureOr<List<OrderModel>> build() async {
    return _fetchOrders();
  }

  Future<List<OrderModel>> _fetchOrders() async {
    try {
      final response = await supabase
          .from('orders')
          .select()
          .order('created_at', ascending: false);
      
      return (response as List).map((json) => OrderModel.fromJson(json)).toList();
    } catch (e, st) {
      print('Order fetch error: $e');
      print(st);
      throw Exception('Koneksi Terputus. Gagal memuat pesanan. Detail: $e');
    }
  }

  Future<void> createOrder(OrderModel order) async {
    state = const AsyncValue.loading();
    try {
      // Exclude generated fields like id and created_at if they are handled by DB
      final payload = order.toJson();
      
      // Fallback for legacy columns in Supabase
      payload['service'] = payload['service'] ?? (order.items.isNotEmpty ? order.items.first.serviceName : 'Multi Layanan');
      payload['weight_kg'] = payload['weight_kg'] ?? (order.items.isNotEmpty ? order.items.first.weightOrQty : 1.0);
      payload['duration'] = payload['duration'] ?? order.durationDays;
      
      // Remove keys that don't exist in Supabase to avoid PGRST204 errors
      payload.remove('duration_days');
      
      // Ensure we don't send `items` if Supabase doesn't have it yet, 
      // but if the user added it as `jsonb`, this would break it. 
      // Based on the error, the first failing column was duration_days.
      // Let's just remove duration_days for now.
      
      // If id is a placeholder or empty, we might want to let Supabase handle it if it generates UUID.
      // Assuming UUID is generated by DB if we omit it, but since it's required in model we might pass it.
      await supabase.from('orders').insert(payload);
      
      // Refresh the list
      state = AsyncValue.data(await _fetchOrders());
    } catch (e, st) {
      print('addOrder error: $e');
      print(st);
      state = AsyncValue.data(state.value ?? []);
      throw Exception('Koneksi Terputus. Gagal menyimpan data. Detail: $e');
    }
  }

  Future<void> updateOrder(OrderModel order) async {
    state = const AsyncValue.loading();
    try {
      final payload = order.toJson();
      
      // Fallback for legacy columns in Supabase
      payload['service'] = payload['service'] ?? (order.items.isNotEmpty ? order.items.first.serviceName : 'Multi Layanan');
      payload['weight_kg'] = payload['weight_kg'] ?? (order.items.isNotEmpty ? order.items.first.weightOrQty : 1.0);
      payload['duration'] = payload['duration'] ?? order.durationDays;
      
      // Remove keys that don't exist in Supabase to avoid PGRST204 errors
      payload.remove('duration_days');
      
      await supabase.from('orders').update(payload).eq('id', order.id);
      
      // Refresh the list
      state = AsyncValue.data(await _fetchOrders());
    } catch (e, st) {
      print('updateOrder error: $e');
      print(st);
      state = AsyncValue.data(state.value ?? []);
      throw Exception('Koneksi Terputus. Gagal menyimpan data. Detail: $e');
    }
  }
}
