import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:laundry_jennaira/shared/models/order_model.dart';
import 'package:laundry_jennaira/core/supabase_client.dart';

part 'order_provider.g.dart';

@riverpod
class OrderNotifier extends _$OrderNotifier {
  @override
  FutureOr<List<OrderModel>> build() async {
    return _fetchOrders();
  }

  Future<List<OrderModel>> _fetchOrders() async {
    try {
      final response = await supabase
          .from('orders')
          .select()
          .order('created_at', ascending: false);
      
      return (response as List).map((json) => OrderModel.fromJson(json)).toList();
    } catch (e) {
      throw Exception('Gagal memuat pesanan: $e');
    }
  }

  Future<void> createOrder(OrderModel order) async {
    state = const AsyncValue.loading();
    try {
      // Exclude generated fields like id and created_at if they are handled by DB
      final payload = order.toJson();
      
      // If id is a placeholder or empty, we might want to let Supabase handle it if it generates UUID.
      // Assuming UUID is generated by DB if we omit it, but since it's required in model we might pass it.
      await supabase.from('orders').insert(payload);
      
      // Refresh the list
      state = AsyncValue.data(await _fetchOrders());
    } catch (e) {
      state = AsyncError(e, StackTrace.current);
      throw Exception('Koneksi Terputus. Data gagal disimpan.');
    }
  }

  Future<void> updateOrder(OrderModel order) async {
    state = const AsyncValue.loading();
    try {
      await supabase.from('orders').update(order.toJson()).eq('id', order.id);
      
      // Refresh the list
      state = AsyncValue.data(await _fetchOrders());
    } catch (e) {
      state = AsyncError(e, StackTrace.current);
      throw Exception('Koneksi Terputus. Data gagal diperbarui.');
    }
  }
}
